kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
    - data

steps:

- name: selenium
  image: selenium/standalone-chrome
  detach: true

- name: getRawData
  image: 2edcovid/python_data_scraping:latest
  environment:
    IMGUR_APIKEY:
      from_secret: imgur_key
  commands:
  - git fetch origin data:data
  - chmod +x wait-for-it.sh
  - ./wait-for-it.sh selenium:4444
  - python fetch_data_files.py
  - python imgur_post.py
  - python utilities/commit_checker.py data

- name: pushInitialData
  image: appleboy/drone-git-push
  when:
    branch: [master]
  settings:
    ssh_key:
      from_secret: ssh_key
    remote_name: origin2
    remote: git@github.com:2edcovid/CovidDataAutomation.git
    branch: data
    local_ref: data

- name: getData
  image: 2edcovid/python_data_scraping:latest
  environment:
    SSHKEY:
      from_secret: gsheet_ssh_key
  commands:
  - python strip_data.py
  - python utilities/commit_checker.py
  - python gsheet_interaction.py

- name: pushData
  image: appleboy/drone-git-push
  when:
    branch: [master]
  settings:
    ssh_key:
      from_secret: ssh_key
    remote_name: origin2
    remote: git@github.com:2edcovid/CovidDataAutomation.git
    branch: data
    local_ref: data




image_pull_secrets:
  - dockerconfig
