version: "3.8"

x-build-python: &build-python
  build:
    context: ./docker
    dockerfile: Dockerfile_python
  working_dir: /tmp
  volumes:
    - ./:/tmp

services:
  selenium:
    build:
      context: ./docker
      dockerfile: Dockerfile_selenium

  python:
    <<: *build-python
    environment: 
    - APIKEY=$APIKEY
    - APIID=$APIID
    - APIPWD=$APIPWD
